import Head from 'next/head'
import Feed from '../components/Feed'
import Auth from '../context/auth'

export default function Home() {
  console.log("Hello.")
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed />
      <Auth/>
    </div>
  )
}