import Head from 'next/head'
import Feed from '../components/Feed'
import { AppContext } from '../context/auth'
import { useContext } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  console.log("Hello.")
  let { user } = useContext(AppContext)
  console.log(user)

  function Redirect() {
    const router = useRouter();
    router.push("/login");
    return null
  }

  function Gaurd(){
    
  }

  return (
    <div>
      <Head>
        <title>Reels Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        user?.uid ? <Feed /> : <Redirect />
      }
    </div>
  )
}